#!/bin/bash

echo "Installing acltest and dependencies...";
pip install -r requirements.txt -e .;

echo "Installing test requirements and their dependencies...";
pip install -r test-requirements.txt;
if [ "$1" == '--hooks' ]; then
    echo "Installing pre-commit and pre-commit hooks";
    pip install -r hook-requirements.txt;
    pre-commit install;
fi
echo "Producing test baseline with pytest...";
pytest --cov=acltest --cov-report term-missing tests/;
