#!/bin/bash

if [ "$1" == "--hooks" ]; then
    echo "Uninstalling pre-commit hooks...";
    pre-commit uninstall;
    echo "Uninstalling pre-commit and its dependencies";
    pip uninstall -r dependencies/hook-requirements.txt -y;
fi

echo "Uninstalling test requirements";
pip uninstall -r dependencies/test-requirements.txt -y;
echo "Uninstalling acltest";
pip uninstall acltest -y;
echo "Uninstalling dependencies";
pip uninstall -r dependencies/requirements.txt -y;
